### ISSUE TITLE
Calculate slide width immediately

### ISSUE THREAD

**Issue by adiba** [faceless-ui/slider#17]
This line:

https://github.com/faceless-ui/slider/blob/68dd7771e3c5f9421bd639f8cf94b39ce32732f9/src/SliderProvider/index.tsx#L85

should instead be:
```ts
const [slideWidth, setSlideWidth] = useState(`${(slidesToShow > 1 ? 1 / slidesToShow : slidesToShow) * 100}%`);
```
to make use of server side rendering without layout shift.

**Comment by jacobsfletch** [comment]
Hey @adiba if I remember correctly we're not initializing slide width because that will cause layout shift the other way around-where `slidesToShow` is dynamic based on window width. For instance on mobile, the slider might initialize showing 3 then immediately jump to showing only 1 because the window width was populated in the browser. We don't have access to window width during initial state. So instead, we simply don't define slide width until we're certain it's unchanging.

**Comment by adiba** [comment]
> Hey @adiba if I remember correctly we're not initializing slide width because that will cause layout shift the other way around-where `slidesToShow` is dynamic based on window width. For instance on mobile, the slider might initialize showing 3 then immediately jump to showing only 1 because the window width was populated in the browser. We don't have access to window width during initial state. So instead, we simply don't define slide width until we're certain it's unchanging.

Are you refering to the responsive slider?
https://github.com/faceless-ui/slider/blob/1e4ab55d4a6b1588c2797db418339ad21a692110/demo/ResponsiveSlider/index.tsx#L18
